GET {{url}}/prod/collections/tz1VgpmwW66LCbskjudK54Zp96vKn2cHjpGN
Accept: application/json

###

GET {{url}}/prod/collections/tz1VgpmwW66LCbskjudK54Zp96vKn2cHjpGN
Accept: application/json

###

GET {{url}}/prod/swaps/tz1VgpmwW66LCbskjudK54Zp96vKn2cHjpGN
Accept: application/json

###
