GET {{url}}/prod/collections/WALLET_ID
Accept: application/json

###

GET {{url}}/prod/collections/WALLET_ID
Accept: application/json

###

GET {{url}}/prod/swaps/WALLET_ID
Accept: application/json

###
